config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
  resources :subjects, except: [:index]
  resources :registrations, except: [:edit]
  resources :sections
  
  get '/registrations/:id/edit/:subject_id', to: 'registrations#edit', as: 'edit_registration'
  post '/registrations/section_list/:subject_id', to: 'registrations#section_list', as: 'section_list'
  get '/users/remove_account', to: 'users#remove_account', as: 'remove_account'  

  root to: 'sections#index', as: 'home'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role?('admin')
        can :manage, :all
      elsif user.has_role?('teacher')
        can :read, Subject
        can :read, Section
        can :manage, Section, :user_id => user.id
        
        user.sections.pluck(:id).each do |section_id|
          can :update, Registration, :section_id => section_id
        end
        can :read, Registration
        
        cannot [:destroy, :create], Registration
      else
        cannot :manage, Section
        can :read, Section
        can :manage, Registration
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :section
  
  validates_presence_of :user, :section
  validates_uniqueness_of :section, scope: [:user_id]

  def display_name
     "#{self.user.name} - #{self.section.subject.course_code} (#{self.section.name})" unless (self.user.blank? || self.section.blank?)
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :subject
  belongs_to :user
  has_many :users, through: :registrations
  has_many :registrations, dependent: :destroy
  
  validates_presence_of :name, :subject
  validates_uniqueness_of :name, scope: [:subject_id]
  
  def subject_name
    self.subject.course_name
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :sections, dependent: :destroy
  has_many :registrations, through: :sections, dependent: :destroy
  

  validates_presence_of :course_code, :course_name
  validates_uniqueness_of :course_code

  def naming
    "#{self.course_code} - #{self.course_name}"
  end
  
  def display_name
    "#{self.course_name}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :registrations, dependent: :destroy
  has_many :sections, through: :registrations
  belongs_to :role
  
  validates_presence_of :name, :username
  validates_uniqueness_of :username
  
  
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= Role.find_by(name: 'student')
  end
  
  def has_role?(role_name)
    self.role.name == role_name
  end
         
  def email_changed?
    false
  end
         
  def email_required?
    false
  end
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
    
  layout :layout_by_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.home_path, :alert => exception.message
  end

  protected
  
  def layout_by_resource
    if devise_controller? && resource_name == :user && action_name == "edit"
      'application'
    end
  end


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :email])
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_registration, only: [:edit, :update, :destroy]
  load_and_authorize_resource
  
  def index
    if current_user.has_role?('student')
      @registrations = Registration.includes(:section => [:subject]).where(user_id: current_user.id)
    elsif current_user.has_role?('teacher')
      @registrations = Registration.joins(:section).where("sections.user_id = #{current_user.id}")
    else
      @registrations = Registration.all
    end
  end
  
  def new
    @subjects = Subject.joins(:sections).distinct
  end
  
  def create
    @registration = Registration.create(registration_params)
    redirect_to registrations_path
  end
  
  def edit
    @sections = Subject.includes(:sections).find(params[:subject_id]).sections
  end
  
  def update
    @registration.update(registration_params)
    redirect_to registrations_path
  end
  
  def destroy
    @registration.destroy
    redirect_to registrations_path
  end
  
  def section_list
    @sections = Subject.find(params[:subject_id]).sections.pluck(:name, :id)
    respond_to do |format|
      format.json { render json: @sections }
    end
  end
  
  private
  
  def set_registration
    @registration = Registration.includes(:user).find(params[:id])
  end
  
  def registration_params
    params.require(:registration).permit(:section_id, :user_id, :grade)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:edit, :update, :destroy]
  load_and_authorize_resource
  
  def index
    @q = Subject.ransack(params[:q])
    @subjects = @q.result.includes(:sections => [:user]).order('sections.name DESC').distinct
  end
  
  def create
    @section = Section.create(section_params)
    flash[:success] = 'Section Created'
    redirect_to sections_path
  end
  
  def edit
  end
  
  def update
    @section.update(section_params)
    flash[:success] = 'Section Updated'
    redirect_to sections_path
  end
  
  def destroy
    @section.destroy
    flash[:success] = 'Section Deleted'
    redirect_to sections_path
  end
  
  private

  def set_section
    @section = Section.find(params[:id])
  end
  
  def section_params
    params.require(:section).permit(:subject_id, :user_id, :name)
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:edit, :update, :destroy]
  load_and_authorize_resource

  def new
    @subject = Subject.new
  end
  
  def create
    @subject = Subject.create(subject_params)
    flash[:alert] = 'Subject Created'
    redirect_to home_path
  end
  
  def edit
  end
  
  def update
    @subject.update(subject_params)
    flash[:alert] = 'Subject Updated'
    redirect_to home_path
  end
  
  def destroy
    @subject.destroy
    flash[:alert] = 'Subject Destroyed'
    redirect_to home_path
  end
  
  private
  
  def set_subject
    @subject = Subject.find(params[:id])
  end
  
  def subject_params
    params.require(:subject).permit(:course_code, :course_name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def remove_account
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grade Management System</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class = 'row'>        
        <div class = 'col-sm-3 col-md-3 col-lg-3'>
          
            <div class = 'list-group'>
               <%= link_to '#collapseOne', class: 'list-group-item text-center dropdown-toggle', data: {toggle: 'collapse'} do %>
                Account Management <span class = 'caret'></span>
               <% end %>
               <div id="collapseOne" class="panel-collapse collapse">
                  <%= link_to "Edit Account", edit_user_registration_path, class: 'list-group-item text-center' %>
                  <%= link_to "Remove Account", remove_account_path, class: 'list-group-item text-center' %>
                </div>
               <% if can? :read, Section %> 
                 <%= link_to "Available Subjects", home_path, class: 'list-group-item text-center' %>
               <% end %>
               <% if can? :read, Registration %>
                 <%= link_to registrations_path, class: 'list-group-item text-center' do %>
                   <%= current_user.has_role?('student') ? "Register Subjects" : "Teaching Subjects"%>
                 <% end %>
               <% end %>
                 <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'list-group-item text-center' %>
            </div>
          
            
        </div>
        <div class = 'col-sm-9 col-md-9 col-lg-9'>
          <div style = 'padding-top: 10px;'>
            <% unless alert.blank? %>
            <div class="alert alert-info alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= alert %>
            </div>
            <% end %>
            <% unless notice.blank? %>
            <div class="alert alert-info alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= notice %>
            </div>
            <% end %>
            <%= yield %>
          </div>
        </div>

        
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog modal-md" role="document">
            <div id="show-modal" class="modal-content">
            </div>
          </div>
        </div>
          
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grade Management System</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = 'body'>
    <% unless alert.blank? %>
    <div class="alert alert-warning alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
    <% end %>
    <% unless notice.blank? %>
    <div class="alert alert-warning alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
    <% end %>
    <div class = 'container padding-top-add'>
      <div class = 'row'>
          <div class="col-xs-3 col-xs-offset-3 col-sm-3 col-sm-offeset-3">
              <div class = 'well'>
                <%= yield %>
              </div>
          </div>
      </div>
    </div>
  </body>
</html>

app/views/roles/_form.html.erb
<%= simple_form_for @role do |f| %>
  <%= f.input :name, label: 'Role Name' %>
  <%= f.button :submit, class: 'btn btn-primary' %>
  <%= link_to "Back", :back, class: 'btn btn-default'%>
<% end %>

app/views/roles/edit.html.erb
<h2>Edit Role</h2>

<%= render 'form'%>

app/views/roles/index.html.erb
<% if can?(:create, Role) %>
<%= link_to 'Add Role', new_role_path, class: 'btn btn-primary'%>
<% end %>
<% if !@roles.blank? %>

<table class = 'table table-responsive table-striped'>
  <thead>
    <th>Name</th>
    <% if can?(:update, Role) && can?(:destroy, Role)%>
    <th colspan = '2'>Actions</th>
    <% end %>
  </thead>

  <% @roles.each do |role|%>
  <tr>
    <td><%= role.name %></td>
    <% if can? :update, Role %>
    <td><%= link_to 'Edit', edit_role_path(role.id), class: 'btn btn-default'%>
    <% end %>
    
    <% if can? :destroy, Role %>
    <%= link_to 'Delete', role_path(role.id), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure?"}%>
    <% end %>
    </td>
  </tr>
  <% end %>
</table>
<% else %>
No Roles Yet.
<% end %>

app/views/roles/new.html.erb
<h2>New Role</h2>

<%= render 'form'%>

app/views/sections/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4 class="modal-title" id="myModalLabel">Edit Section</h4>
</div>
<%= render 'form'%>

app/views/sections/_form.html.erb
<%= simple_form_for @section do |f| %>
<div class="modal-body">
  <%= f.input :name, label: 'Section' %>
  <%= f.input :subject_id, collection: Subject.all, label_method: :course_name, label: 'Subject', include_blank: false %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
</div>
<div class = 'modal-footer'>
  <%= f.button :submit, class: 'btn btn-primary' %>
  <%= link_to "Back", :back, class: 'btn btn-default'%>
</div>
<% end %>

app/views/sections/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4 class="modal-title" id="myModalLabel">New Section</h4>
</div>

<%= render 'form'%>

app/views/sections/edit.js.erb
$("#show-modal").html('<%= j render "edit" %>')

app/views/sections/index.html.erb
<%= search_form_for @q, url: home_path, :builder => SimpleForm::FormBuilder do |f| %>
<div class = 'input-group'>
  <div class="input-group-btn">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class = 'search_text'>Course Name</span>
      <span class="caret"></span></button>
    </button>
    <ul class="dropdown-menu" id="search_dropdown">
      <li class="dropdown-item active"><a href="#">Course Name</a><li>
      <li class="dropdown-item"><a href="#">Course Code</a></li>
    </ul>
  </div>
  <%= f.search_field :course_name_cont, class: 'form-control search_field' %>
  <div class="input-group-btn">
    <%= f.submit "Search", class: 'btn btn-primary' %>
  </div>
</div>
<% end %>
<br>

<% if can?(:create, Section) || can?(:create, Subject) %>
  <div style = 'padding-bottom: 20px;'>
  <% if can? :create, Section %>
  <%= link_to 'Add Section', new_section_path, class: 'btn btn-primary', remote: true, data: {toggle: "modal", target: "#myModal"} %>
  <% end %>

  <% if can? :create, Subject %>
  <%= link_to 'Add Subject', new_subject_path, class: 'btn btn-primary', remote: true, data: {toggle: "modal", target: "#myModal"} %>
  <% end %>
  </div>
<% end %>
<div id = 'modal-display'></div>

<% if !@subjects.blank? %>
    <% @subjects.each_with_index do |subject, index|%>
    <div class="panel-group">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <div class = 'col-md-6 col-xs-6 col-sm-6 col-lg-6'>
              <div class = 'pull-left'>
            <a data-toggle="collapse" href="#collapse<%= index %>"><%= subject.naming %> </a>
              </div>
            </div>
            <div class = 'col-md-6 col-xs-6 col-sm-6 col-lg-6'>
              <div class = 'pull-right'>
            <% if can? :update, Subject %>
            <%= link_to 'Edit', edit_subject_path(subject.id), class: 'btn btn-default', remote: true, data: {toggle: "modal", target: "#myModal"}%>
            <% end %>
            <% if can? :destroy, Subject %>
            <%= link_to 'Delete', subject_path(subject.id), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure?"}%>
            <% end %>
              </div>
            </div>
            <div class = 'clearfix'></div>
          </h4>
        </div>
        <div id="collapse<%= index %>" class="panel-collapse collapse <%= "in" if subject.sections.present? %>">
          <ul class="list-group">
            <% if subject.sections.present? %>
              <% subject.sections.each do |section|%>
              <li class="list-group-item">
                <div class = 'col-md-6 col-xs-6 col-sm-6 col-lg-6'>
                  <div class = 'pull-left'>
                  <%= section.name %> 
                  </div>
                  <div class = 'pull-right'>
                    <% if section.user.present? %>
                    <%= section.user.username %>
                    <% else %>
                    <%= "TBA" %>
                    <% end %>
                  </div>
                </div>
                
                <div class = 'col-md-6 col-xs-6 col-sm-6 col-lg-6'>
                  <div class = 'pull-right'>
                      <% if can? :update, Section %>
                      <%= link_to 'Edit', edit_section_path(section.id), class: 'btn btn-default', remote: true, data: {toggle: "modal", target: "#myModal"}%>
                      <% end %>
                      <% if can? :delete, Section %>
                      <%= link_to 'Delete', section_path(section.id), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure?"}%><br>
          
                    <% end %>
                  </div>
                </div>
                <div class = 'clearfix'></div>
              </li>
              <% end %>
            <% else %>
              <li class="list-group-item">
                No sections available for this subject.
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <% end %>
<% else %>
No Sections Yet.
<% end %>

app/views/sections/new.js.erb
$("#show-modal").html('<%= j render "new" %>')

app/views/subjects/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4 class="modal-title" id="myModalLabel">Edit Subject</h4>
</div>
<%= render 'form'%>

app/views/subjects/_form.html.erb
<%= simple_form_for @subject do |f| %>
<div class="modal-body">
  <%= f.input :course_name, label: 'Course Name' %>
  <%= f.input :course_code, label: 'Course Code' %>
</div>
<div class = 'modal-footer'>
  <%= f.button :submit, class: 'btn btn-primary' %>
  <%= link_to "Back", :back, class: 'btn btn-default'%>
</div>
<% end %>

app/views/subjects/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4 class="modal-title" id="myModalLabel">New Subject</h4>
</div>
<%= render 'form'%>

app/views/subjects/edit.js.erb
$("#show-modal").html('<%= j render "edit" %>')

app/views/subjects/new.js.erb
$("#show-modal").html('<%= j render "new" %>')

app/views/users/remove_account.html.erb
<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", user_registration_path, data: { confirm: "Are you sure?" }, method: :delete %></p>